
  -- First, remove the table if it exists
drop table if exists bookmark;

-- Create the table anew
create table bookmark (
  id INTEGER primary key generated by default as identity,
  name text,
  description text
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmark (name,description)
values
  ('Thinkful', 'Programming school'),
  ('Google', 'What people use when there lost'),
  ('Myspace', 'The place that used to exsist'),
  ('Yahoo', 'Lost art'),
  ('Youtube', 'A school for Everything'),
  ('CODEWars', 'Programming challeneges'),
  ('Twitter', 'Not actually a bird'),
  ('Odin', 'Programming school'),
  ('Pintrest', 'Art school');